# Use a imagem base do OpenJDK
FROM openjdk:11-jdk-slim

# Defina o diretório de trabalho
WORKDIR /app

# Copie o arquivo JAR gerado para o contêiner
COPY target/tourist-spot-0.0.1-SNAPSHOT.jar app.jar

# Comando para executar a aplicação
ENTRYPOINT java -jar target/tourist-spot-0.0.1-SNAPSHOT.jar


