# Use a imagem base do OpenJDK 11
FROM openjdk:11-jdk-slim

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o arquivo JAR gerado pelo Maven/Gradle para o contêiner
COPY /target/tourist-spot-0.0.1-SNAPSHOT.jar app.jar

# Comando para executar a aplicação Spring Boot
ENTRYPOINT ["java", "-jar", "app.jar"]


