# fly.toml file generated for TouristSpot application on Fly.io

app = "touristspot"

# Primary region where the app will be deployed
primary_region = "iad"

# Configuration for the build process
[build]
  builder = "paketobuildpacks/builder:base"

# Define environment variables
[env]
  SPRING_DATASOURCE_URL = "jdbc:h2:mem:touristspotdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
  SPRING_DATASOURCE_USERNAME = "sa"
  SPRING_DATASOURCE_PASSWORD = ""
  SPRING_DATASOURCE_DRIVER_CLASS_NAME = "org.h2.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO = "update"
  SPRING_JPA_DATABASE_PLATFORM = "org.hibernate.dialect.H2Dialect"
  # Add other environment variables as needed

# Define services and their settings
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.tcp_checks]
    interval = 10000
    timeout = 2000
    grace_period = "1s"
    restart_limit = 0

# Define the volumes (if any)
[[mounts]]
  source = "touristspot_data"
  destination = "/data"
